name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action builds your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
branding:
  color: red
  icon: wifi
inputs:
  command:
    description: "Command to run in ESP-IDF docker (default: idf.py all)"
    type: string
    default: "idf.py all"
    required: false
  esp_idf_version:
    description: "Espressif IoT Development Framework version"
    type: string
    required: false
    default: "latest"
  esp_target:
    description: "ESP32 chip target"
    type: string
    required: false
    default: "esp32"
  path:
    description: "Relative path under GITHUB_WORKSPACE to place the repository"
    type: string
    default: ""
    required: false
  env-file:
    description: "Path to env vars file, relative to GITHUB_WORKSPACE"
    type: string
    required: false
    default: "esp-idf-build.env"

runs:
  using: "composite"
  steps:
    - run: |
        export IDF_TARGET=$(echo "${{ inputs.esp_target }}" | tr '[:upper:]' '[:lower:]' | tr -d '_-')
        touch "esp-idf-build.env"
        docker run -t -e IDF_TARGET="${IDF_TARGET}" --env-file "esp-idf-build.env" \
          --env-file "${GITHUB_WORKSPACE}/${{ inputs.env-file }}" \
          --workdir "/app/${{ github.repository }}/${{ inputs.path }}" \
          --volume "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" \
          espressif/idf:${{ inputs.esp_idf_version }} \
          /bin/bash -c 'git config --global --add safe.directory "*" && ${{ inputs.command }}'
      shell: bash
